# Generated by Django 6.0.3 on 2026-04-03 00:00

from django.db import migrations


class Migration(migrations.Migration):
    """
    Empty migration: can_* fields are already included in 0001_initial.py.
    This file is kept to avoid breaking migration history references.
    """

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = []

