# Generated by Django 6.0.3 on 2026-04-07 16:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalNotification",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("budget_overrun", "Dépassement de budget"),
                            ("budget_threshold", "Seuil de budget atteint"),
                            ("deadline_approaching", "Délai approchant"),
                            ("project_overdue", "Projet en retard"),
                            ("status_change", "Changement de statut"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID du projet lié"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "date_created",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="Date création",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Notification",
                "verbose_name_plural": "Historiques Notifications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "notify_budget_overrun",
                    models.BooleanField(
                        default=True, verbose_name="Notifier le dépassement de budget"
                    ),
                ),
                (
                    "notify_budget_threshold",
                    models.BooleanField(
                        default=True, verbose_name="Notifier les seuils de budget"
                    ),
                ),
                (
                    "notify_deadline_approaching",
                    models.BooleanField(
                        default=True, verbose_name="Notifier les délais approchants"
                    ),
                ),
                (
                    "notify_project_overdue",
                    models.BooleanField(
                        default=True, verbose_name="Notifier les projets en retard"
                    ),
                ),
                (
                    "notify_status_change",
                    models.BooleanField(
                        default=True, verbose_name="Notifier les changements de statut"
                    ),
                ),
                (
                    "budget_threshold_percent",
                    models.PositiveIntegerField(
                        default=80,
                        help_text="Envoyer une alerte quand les dépenses atteignent ce % du budget",
                        verbose_name="Seuil d'alerte budget (%)",
                    ),
                ),
                (
                    "deadline_alert_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Alerter X jours avant la date de fin"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date création"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date modification"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Préférence Notification",
                "verbose_name_plural": "Historiques Préférences Notifications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("budget_overrun", "Dépassement de budget"),
                            ("budget_threshold", "Seuil de budget atteint"),
                            ("deadline_approaching", "Délai approchant"),
                            ("project_overdue", "Projet en retard"),
                            ("status_change", "Changement de statut"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID du projet lié"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date création"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notify_budget_overrun",
                    models.BooleanField(
                        default=True, verbose_name="Notifier le dépassement de budget"
                    ),
                ),
                (
                    "notify_budget_threshold",
                    models.BooleanField(
                        default=True, verbose_name="Notifier les seuils de budget"
                    ),
                ),
                (
                    "notify_deadline_approaching",
                    models.BooleanField(
                        default=True, verbose_name="Notifier les délais approchants"
                    ),
                ),
                (
                    "notify_project_overdue",
                    models.BooleanField(
                        default=True, verbose_name="Notifier les projets en retard"
                    ),
                ),
                (
                    "notify_status_change",
                    models.BooleanField(
                        default=True, verbose_name="Notifier les changements de statut"
                    ),
                ),
                (
                    "budget_threshold_percent",
                    models.PositiveIntegerField(
                        default=80,
                        help_text="Envoyer une alerte quand les dépenses atteignent ce % du budget",
                        verbose_name="Seuil d'alerte budget (%)",
                    ),
                ),
                (
                    "deadline_alert_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Alerter X jours avant la date de fin"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date modification"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence de notification",
                "verbose_name_plural": "Préférences de notification",
            },
        ),
    ]
