# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depense", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="frais_de_service",
            field=models.BooleanField(default=False, verbose_name="Frais de service"),
        ),
        migrations.AddField(
            model_name="expense",
            name="frais_de_service_valeur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valeur des frais de service",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="frais_de_service_type",
            field=models.CharField(
                choices=[("percentage", "Pourcentage"), ("fixed", "Fixe")],
                default="fixed",
                max_length=20,
                verbose_name="Type des frais de service",
            ),
        ),
        migrations.AddField(
            model_name="historicalexpense",
            name="frais_de_service",
            field=models.BooleanField(default=False, verbose_name="Frais de service"),
        ),
        migrations.AddField(
            model_name="historicalexpense",
            name="frais_de_service_valeur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valeur des frais de service",
            ),
        ),
        migrations.AddField(
            model_name="historicalexpense",
            name="frais_de_service_type",
            field=models.CharField(
                choices=[("percentage", "Pourcentage"), ("fixed", "Fixe")],
                default="fixed",
                max_length=20,
                verbose_name="Type des frais de service",
            ),
        ),
    ]
