# Generated by Django 6.0.4 on 2026-06-06 09:07

import depense.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depense", "0002_expense_service_fees"),
        (
            "project",
            "0002_alter_historicalproject_status_alter_project_status_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="project.supplier",
                verbose_name="Fournisseur référencé",
            ),
        ),
        migrations.AddField(
            model_name="historicalexpense",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="project.supplier",
                verbose_name="Fournisseur référencé",
            ),
        ),
        migrations.CreateModel(
            name="ExpenseAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=depense.models.expense_attachment_upload_to,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Libellé"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="depense.expense",
                        verbose_name="Dépense",
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_attachments_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ajouté par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe dépense",
                "verbose_name_plural": "Pièces jointes dépenses",
                "ordering": ("-date_created", "-id"),
            },
        ),
    ]
