# Generated by Django 6.0.6 on 2026-06-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("depense", "0004_backfill_suppliers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="fournisseur",
        ),
        migrations.RemoveField(
            model_name="historicalexpense",
            name="fournisseur",
        ),
    ]
