# Generated by Django 6.1.1 on 2026-10-03 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depense", "0005_remove_expense_fournisseur_and_more"),
        ("devis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="expenses",
                to="devis.quote",
                verbose_name="Devis",
            ),
        ),
        migrations.AddField(
            model_name="historicalexpense",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="devis.quote",
                verbose_name="Devis",
            ),
        ),
    ]
