# Generated by Django 6.0.4 on 2026-06-06 09:07

import django.db.models.deletion
import revenu.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revenu", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=revenu.models.revenue_attachment_upload_to,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Libellé"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "revenue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="revenu.revenue",
                        verbose_name="Revenu",
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenue_attachments_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ajouté par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe revenu",
                "verbose_name_plural": "Pièces jointes revenus",
                "ordering": ("-date_created", "-id"),
            },
        ),
    ]
