# Generated by Django 6.1.1 on 2026-10-03 10:45

import devis.models
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0006_client_ville_historicalclient_ville_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalQuote",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("number", models.CharField(max_length=100)),
                ("date", models.DateField(db_index=True)),
                ("description", models.TextField()),
                (
                    "amount_ht",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "amount_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount_ttc",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Reçu"),
                            ("validated", "Validé"),
                            ("rejected", "Refusé"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, editable=False)),
                ("date_updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="project.category",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="project.project",
                    ),
                ),
                (
                    "sous_categorie",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="project.subcategory",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="project.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Devis",
                "verbose_name_plural": "historical Devis",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=100)),
                ("date", models.DateField(db_index=True)),
                ("description", models.TextField()),
                (
                    "amount_ht",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "amount_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount_ttc",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Reçu"),
                            ("validated", "Validé"),
                            ("rejected", "Refusé"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="project.category",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="project.project",
                    ),
                ),
                (
                    "sous_categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="project.subcategory",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="project.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
                "ordering": ("-date", "-id"),
            },
        ),
        migrations.CreateModel(
            name="QuoteAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=devis.models.quote_attachment_upload_to,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Libellé"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="devis.quote",
                        verbose_name="Devis",
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_attachments_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ajouté par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe devis",
                "verbose_name_plural": "Pièces jointes devis",
                "ordering": ("-date_created", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_ht__gt", 0), ("amount_tva__gte", 0)),
                name="quote_positive_amounts",
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "amount_ttc",
                        django.db.models.expressions.CombinedExpression(
                            models.F("amount_ht"), "+", models.F("amount_tva")
                        ),
                    )
                ),
                name="quote_ttc_matches",
            ),
        ),
    ]
