# Generated by Django 6.0.4 on 2026-06-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_historicalprojectrealbudgetentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="ville",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Ville"
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="ville",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Ville"
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="ville_client",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Ville du client"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="ville_client",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Ville du client"
            ),
        ),
    ]
