# Generated by Django 6.0.3 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WsMaintenanceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance",
                    models.BooleanField(
                        default=False,
                        verbose_name="Maintenance",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
            ],
            options={
                "verbose_name": "Maintenance",
                "verbose_name_plural": "Maintenance",
            },
        ),
    ]
